#!/bin/sh
#
## HTTP(S) URL handler for Firejail
#+ uses inotifywait to watch HTTP(S) URL drop file activity from outside the sandbox
#+ and relays the URL to a configured web browser via a custom xdg-open wrapper

# shellcheck disable=SC2154

### vars
## source common settings
_settings_file="firejail-handler-settings-http.inc"
if [ -f "${HOME}/.config/firejail/${_settings_file}" ]; then
    #+ use settings defined by user
    . "${HOME}/.config/firejail/${_settings_file}"
elif [ -f "/etc/firejail/${_settings_file}" ]; then
    #+ use system-wide settings
    . "/etc/firejail/${_settings_file}"
else
    #+ fall back to hard-coded values
    _browser_bin="/usr/bin/firefox"
    _debug=0
    if [ "$(which xdg-user-dir)" ]; then
	_drop_dir="$(xdg-user-dir DOWNLOAD)"
    else
	_xdg_config_home="$(env | grep -c "XDG_CONFIG_HOME")"
	if [ "$_xdg_config_home" = 1 ]; then
	    if [ -s "${XDG_CONFIG_HOME}/user-dirs.dirs" ]; then
		_drop_dir="$(grep "^XDG_DOWNLOAD_DIR=" "${XDG_CONFIG_HOME}/user-dirs.dirs" | awk '{split($0,a,"="); print a[2]}' | sed 's/"//g')"
	    fi
	elif [ -s "${HOME}/.config/user-dirs.dirs" ]; then
	    _drop_dir="$(grep "^XDG_DOWNLOAD_DIR=" "${HOME}/.config/user-dirs.dirs" | awk '{split($0,a,"="); print a[2]}' | sed 's/"//g')"
	else
	    _drop_dir="${HOME}/Downloads"
	fi
    fi
    _drop_dir="${_drop_dir}/.firejail-dropzone"
    _drop_file="${_drop_dir}/firejail.drop"
    _xdg_open_wrapper_bin="/usr/local/bin/xdg-open"
fi


### logic
# ensure drop location exists
[ ! -d "$_drop_dir" ] && mkdir -p "$_drop_dir"

# ensure needed commands are available
for _cmd in "inotifywait" "xdg-open"; do
    if [ ! -x "/usr/bin/${_cmd}" ]; then
	echo "Command not found: /usr/bin/${_cmd} - aborting"
	exit 1
    fi
done
for _cmd in "$_browser_bin" "$_xdg_open_wrapper_bin"; do
    if [ ! -x "$_cmd" ]; then
	echo "Command not found: ${_cmd} - aborting"
	exit 1
    fi
done

# watch drop file for modifications
[ -e "$_drop_file" ] && rm -f "$_drop_file"
touch "$_drop_file"
inotifywait -m -e modify --format '%f' "$_drop_file" | while read -r line
do
    if [ -s "$_drop_file" ]; then
	# get URL
	_url="$(head -n 1 "$_drop_file")"
	# open URL
	"$_xdg_open_wrapper_bin" "$_url"
	# reset
	truncate -s 0 "$_drop_file"
    fi
done

exit 0
