#!/bin/sh
#
## HTTP(S) URL handler for Firejail
#+ point your sandboxed application to this script for easy HTTP(S) URL relaying
#+ (1) this script saves a URL at a read/write accessible location inside the sandbox
#+ (2) from outside the sandbox `firejail-url-handler-ctl` picks up that URL
#+ and opens it in the configured web browser via a custom xdg-open wrapper
#+ (defaults to firefox)

# shellcheck disable=SC2154

# bail if we didn't get a URL
[ -z "$1" ] && exit 1

### vars
# source common settings
. "firejail-handler-settings-http.inc"


### logic
# create drop
echo "$1" > "$_drop_file"

exit 0
